version: "3.8"
services:
  postgres:
    image: postgres:15.14-alpine
    container_name: reme-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: remember_me_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  hasura:
    image: hasura/graphql-engine:v2.48.11
    container_name: reme-hasura
    ports:
      - "8081:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://admin:admin@host.docker.internal:5432/remember_me_db
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      ## uncomment next line to run console offline (i.e load console assets from server instead of CDN)
      # HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
      HASURA_GRAPHQL_DB_URL_FROM_ENV: "true"
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
    depends_on:
      - postgres

  keycloak:
    image: docker.io/keycloak/keycloak:26.4
    container_name: reme-keycloak
    command: ["start-dev"]
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    
volumes:
  pgdata:
  keycloak_data:
