mutation InsertUser($mail: String!, $name: String!, $preferences: jsonb!) {
  insert_User(objects: { Mail: $mail, Name: $name, Preferences: $preferences }) {
    returning {
      Id,
      Name
    }
  }
}

query GetUserByMail($mail: String!) {
  User(where: {Mail: {_eq: $mail}}) {
    Id,
    Name
  }
}
