name: Unit Tests
on: 
  pull_request:
    branches: [ develop ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Install dependencies
      run: npm ci

    - name: Run unit tests
      run: npm run test-workflow